#!/bin/sh
echo "🔎 Checking commit message format..."
# commit_msg_file="$1"
# commit_msg=$(cat "$commit_msg_file")

# pattern="^((feat|fix|chore|docs|style|refactor|test|ci|build)(\\(.*\\))?: .{1,50})"
# if ! echo "$commit_msg" | grep -Eq "$pattern"; then
#   echo "❌ Commit message does not follow Conventional Commit format."
#   echo "   Example: 'feat(scope): add new feature'"
#   exit 1
# fi
echo "✅ Commit message format is correct."
