#!/bin/sh

echo "📢 Notifying Teams on Slack..."

# Extract the Slack Webhook URL from the environment variable
SLACK_WEBHOOK_URL="$SLACK_WEBHOOK_URL"

# Check if the Slack Webhook URL is set
if [ -z "$SLACK_WEBHOOK_URL" ]; then
  echo "❌ SLACK_WEBHOOK_URL is not set. Please set the environment variable and try again."
  exit 1
fi

# Get commit details
commit_hash=$(git log -1 --format="%H")
commit_author=$(git log -1 --format="%an")
commit_message=$(git log -1 --format="%s")

# Slack message payload
payload="{
  \"text\": \"New commit made by $commit_author: $commit_message. Commit hash: $commit_hash\"
}"

# Send notification to Slack
curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"

echo "✅ Slack notification sent."
