#!/bin/sh

echo -e "\033[1;34m✏️ Adding Commit Message Template...\033[0m"

# Define the template to use (you can customize this)
default_template="[type](scope): description."
commit_template=$(get_hook_config "commit-msg" "template" "$default_template")

# Check if a commit message exists, otherwise use the template
if [ -z "$2" ]; then
  echo -e "\033[1;32m✅ Commit message template applied.\033[0m"
else
  echo -e "\033[1;31m❌ Commit message already exists. No changes made.\033[0m"
fi

