#!/bin/sh

echo -e "\033[1m🧪 Running Unit Tests...\033[0m"

# Check if npm test command is available
if ! command -v npm &> /dev/null; then
  echo -e "\033[1;31m❌ npm not found! Ensure Node.js and npm are installed.\033[0m"
  exit 1
fi

# Run unit tests
CI=true npm test
if [ $? -ne 0 ]; then
  echo -e "\033[1;31m❌ Unit tests failed. Fix errors before committing.\033[0m"
  exit 1
fi

echo -e "\033[1;32m✅ All unit tests passed successfully.\033[0m"
